Let's load the dataset.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [2]:
dataset = pd.read_csv('play_dataset.csv')
dataset = dataset.drop(columns = 'Unnamed: 0')
dataset

tipologia genere        zona  bagno  cucina  salotto  balcone range euro
0      doppia      F       Murri      2       1        0        0    200-225
1      doppia      F     Marconi      2       1        1        0    225-250
2      doppia    M/F   Bolognina      1       1        1        0    250-275
3     singola      F    S.Vitale      1       1        0        1    400-425
4     singola      F     Irnerio      1       1        0        1    500-525
..        ...    ...         ...    ...     ...      ...      ...        ...
195    doppia      M     Irnerio      1       1        0        0    200-225
196    doppia    M/F   Bolognina      2       1        1        1    225-250
197    doppia    M/F   Bolognina      1       1        1        1    225-250
198   singola    M/F  San Donato      1       1        0        0    350-375
199   singola    M/F        Lame      1       1        0        0    325-350

[200 rows x 8 columns]

In [3]:
dummy_dataset = pd.get_dummies(dataset, columns = ['tipologia', 'genere', 'zona'])
columns = list(dummy_dataset.columns.values)
columns.pop(columns.index('range euro')) 
dummy_dataset = dummy_dataset[columns+['range euro']]
dummy_dataset

bagno  cucina  salotto  balcone  tipologia_doppia  tipologia_singola  \
0        2       1        0        0                 1                  0   
1        2       1        1        0                 1                  0   
2        1       1        1        0                 1                  0   
3        1       1        0        1                 0                  1   
4        1       1        0        1                 0                  1   
..     ...     ...      ...      ...               ...                ...   
195      1       1        0        0                 1                  0   
196      2       1        1        1                 1                  0   
197      1       1        1        1                 1                  0   
198      1       1        0        0                 0                  1   
199      1       1        0        0                 0                  1   

     genere_F  genere_M  genere_M/F  zona_Barca  ...  zona_Malpighi  \
0           1         0           0           0  ...              0   
1           1         0           0           0  ...              0   
2           0         0           1           0  ...              0   
3           1         0           0           0  ...              0   
4           1         0           0           0  ...              0   
..        ...       ...         ...         ...  ...            ...   
195         0         1           0           0  ...              0   
196         0         0           1           0  ...              0   
197         0         0           1           0  ...              0   
198         0         0           1           0  ...              0   
199         0         0           1           0  ...              0   

     zona_Marconi  zona_Mazzini  zona_Murri  zona_S.Ruffillo  zona_S.Viola  \
0               0             0           1                0             0   
1               1             0           0                0             0   
2               0             0           0                0             0   
3               0             0           0                0             0   
4               0             0           0                0             0   
..            ...           ...         ...              ...           ...   
195             0             0           0                0             0   
196             0             0           0                0             0   
197             0             0           0                0             0   
198             0             0           0                0             0   
199             0             0           0                0             0   

     zona_S.Vitale  zona_Saffi  zona_San Donato  range euro  
0                0           0                0     200-225  
1                0           0                0     225-250  
2                0           0                0     250-275  
3                1           0                0     400-425  
4                0           0                0     500-525  
..             ...         ...              ...         ...  
195              0           0                0     200-225  
196              0           0                0     225-250  
197              0           0                0     225-250  
198              0           0                1     350-375  
199              0           0                0     325-350  

[200 rows x 28 columns]

In [4]:
array = dummy_dataset.values
X_enc = array[:,0:27]
Y = array[:,27]

In [5]:
le = preprocessing.LabelEncoder()
le.fit_transform(['175-200', '200-225', '225-250', '250-275', '275-300', '300-325', '325-350', '350-375',
                  '375-400', '400-425', '425-450', '450-475', '475-500', '500-525', '525-550', '550-575', 
                 '575-600', '600-625', '625-650', '650-675', '675-700'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
Y_enc = le.transform(Y)

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X_enc, Y_enc, test_size = 0.13, random_state = 843)

In [8]:
X_test

array([[2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0],
       [2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [2, 1, 1, 1, 

Let's play.

In [9]:
GNB_model = GaussianNB(var_smoothing = 1.057)
GNB_model.fit(X_train, Y_train)

GaussianNB(var_smoothing=1.057)

In [10]:
GNB_accuracy = GNB_model.score(X_test, Y_test)
print("Accuracy: %.3f%%" % (GNB_accuracy*100.0))

Accuracy: 53.846%


In [11]:
from IPython.display import display

In [12]:
def features(bagno, cucina, salotto, balcone, tipologia, genere, zona):
    return bagno, cucina, salotto, balcone, tipologia, genere, zona

In [77]:
w = interact(features, bagno = (0,3,1) , cucina = (0,3,1) , salotto = (0,3,1), balcone = (0,3,1),
                tipologia = ['singola', 'doppia'], genere = ['F', 'M', 'M/F'], 
               zona = ['Barca', 'Bolognina', 'Borgo Panigale', 'Colli', 'Corticella', 'Costa Saragozza', 'Galvani',
                      'Irnerio', 'Lame', 'Malpighi', 'Marconi', 'Mazzini', 'Murri', 'S.Ruffillo', 'S.Viola',
                      'S.Vitale', 'Saffi', 'San Donato'])

interactive(children=(IntSlider(value=1, description='bagno', max=3), IntSlider(value=1, description='cucina',…

In [14]:
display(w)

interactive(children=(IntSlider(value=1, description='bagno', max=3), IntSlider(value=1, description='cucina',…

In [15]:
w.result

(1, 1, 1, 1, 'singola', 'F', 'Barca')

In [16]:
X_new_test = []

for i in range(0, 7):
    if(i<4):
        X_new_test.append(w.result[i])
    else:
        if(w.result[i] == 'singola' or w.result[i] == 'doppia'):
            if(w.result[i] == 'singola'):
                X_new_test.append(0)
                X_new_test.append(1)
            if(w.result[i] == 'doppia'):
                X_new_test.append(1)
                X_new_test.append(0)
        if(w.result[i] == 'F' or w.result[i] == 'M' or w.result[i] == 'M/F'):
            if(w.result[i] == 'F'):
                X_new_test.append(1)
                X_new_test.append(0)
                X_new_test.append(0)
            if(w.result[i] == 'M'):
                X_new_test.append(0)
                X_new_test.append(1)
                X_new_test.append(0)
            if(w.result[i] == 'M/F'):
                X_new_test.append(0)
                X_new_test.append(0)
                X_new_test.append(1)
        if(w.result[i] == 'Barca' or w.result[i] == 'Bolognina' or w.result[i] == 'Borgo Panigale' or
          w.result[i] == 'Colli' or w.result[i] == 'Corticella' or w.result[i] == 'Costa Saragozza'
           or w.result[i] == 'Galvani' or w.result[i] == 'Irnerio' or w.result[i] == 'Lame'
           or w.result[i] == 'Malpighi' or w.result[i] == 'Marconi' or w.result[i] == 'Mazzini'
           or w.result[i] == 'Murri' or w.result[i] == 'S.Ruffillo' or w.result[i] == 'S.Viola'
           or w.result[i] == 'S.Vitale' or w.result[i] == 'Saffi' or w.result[i] == 'San Donato'):
            if(w.result[i] == 'Barca'):
                X_new_test.append(1)
                for o in range(0,17):
                    X_new_test.append(0)
            if(w.result[i] == 'Bolognina'):
                X_new_test.append(0)
                X_new_test.append(1)
                for o in range(0,16):
                    X_new_test.append(0)
            if(w.result[i] == 'Borgo Panigale'):
                for o in range(0,2):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,15):
                    X_new_test.append(0)
            if(w.result[i] == 'Colli'):
                for o in range(0,3):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,14):
                    X_new_test.append(0)
            if(w.result[i] == 'Corticella'):
                for o in range(0,4):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,13):
                    X_new_test.append(0)
            if(w.result[i] == 'Costa Saragozza'):
                for o in range(0,5):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,12):
                    X_new_test.append(0)
            if(w.result[i] == 'Galvani'):
                for o in range(0,6):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,11):
                    X_new_test.append(0)
            if(w.result[i] == 'Irnerio'):
                for o in range(0,7):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,10):
                    X_new_test.append(0)
            if(w.result[i] == 'Lame'):
                for o in range(0,8):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,9):
                    X_new_test.append(0)
            if(w.result[i] == 'Malpighi'):
                for o in range(0,9):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,8):
                    X_new_test.append(0)
            if(w.result[i] == 'Marconi'):
                for o in range(0,10):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,7):
                    X_new_test.append(0)
            if(w.result[i] == 'Mazzini'):
                for o in range(0,11):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,6):
                    X_new_test.append(0)
            if(w.result[i] == 'Murri'):
                for o in range(0,12):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,5):
                    X_new_test.append(0)
            if(w.result[i] == 'S.Ruffillo'):
                for o in range(0,13):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,4):
                    X_new_test.append(0)
            if(w.result[i] == 'S.Viola'):
                for o in range(0,14):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,3):
                    X_new_test.append(0)
            if(w.result[i] == 'S.Vitale'):
                for o in range(0,15):
                    X_new_test.append(0)
                X_new_test.append(1)
                for o in range (0,2):
                    X_new_test.append(0)
            if(w.result[i] == 'Saffi'):
                for o in range(0,16):
                    X_new_test.append(0)
                X_new_test.append(1)
                X_new_test.append(0)
            if(w.result[i] == 'San Donato'):
                for o in range(0,17):
                    X_new_test.append(0)
                X_new_test.append(1)       

In [17]:
X_new_test

[1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [18]:
np.shape(X_new_test)

(27,)

In [19]:
X_new_test = np.transpose(X_new_test)

In [134]:
X_new_test

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [138]:
X_new_test = np.vstack([X_new_test, X_new_test])

In [139]:
X_new_test

array([[1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0]])

In [140]:
GNB_model.predict(X_new_test)

array([9, 9])

In [143]:
Y_new_test = le.inverse_transform(GNB_model.predict(X_new_test))

In [144]:
Y_new_test

array(['400-425', '400-425'], dtype='<U7')

In [21]:
X_train

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [2, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 1]], dtype=object)

In [22]:
X_train.shape

(174, 27)

In [23]:
X_train.dtype

dtype('O')

In [24]:
type(X_train)

numpy.ndarray

In [25]:
type(X_test)

numpy.ndarray

In [26]:
X_train = np.vstack([X_train, X_new_test])

In [27]:
X_train.shape

(175, 27)

In [43]:
display(w)

interactive(children=(IntSlider(value=1, description='bagno', max=3), IntSlider(value=2, description='cucina',…

In [189]:
bagno = widgets.Dropdown(description = 'bagno', options = [0, 1, 2, 3] , continous_update = True)
cucina = widgets.Dropdown(description = 'cucina', options = [0, 1, 2, 3] , continous_update = True)
salotto = widgets.Dropdown(description = 'salotto', options = [0, 1, 2, 3] , continous_update = True)
balcone = widgets.Dropdown(description = 'balcone', options = [0, 1, 2, 3] , continous_update = True)
tipologia = widgets.Dropdown(description = 'tipologia', options = ['singola', 'doppia'])
genere = widgets.Dropdown(description = 'genere', options = ['F', 'M', 'M/F'])
zona = widgets.Dropdown(description = 'zona', options = ['Barca', 'Bolognina', 'Borgo Panigale',
                                                         'Colli', 'Corticella', 'Costa Saragozza',
                                                         'Galvani', 'Irnerio', 'Lame',
                                                         'Malpighi', 'Marconi', 'Mazzini',
                                                         'Murri', 'S.Ruffillo', 'S.Viola',
                                                         'S.Vitale', 'Saffi', 'San Donato'])

y_n = widgets.Dropdown(description = 'Hai scelto?', options = ['Sì', 'No'], value = 'No', continous_update = True)

new_test_batch = []

def features(bagno, cucina, salotto, balcone, tipologia, genere, zona, y_n):
    print('bagno:{} \ncucina:{} \nsalotto:{} \nbalcone:{} \ntipologia:{} \ngenere:{} \nzona:{}'
          .format(bagno, cucina, salotto, balcone, tipologia, genere, zona))
    features = [bagno, cucina, salotto, balcone, tipologia, genere, zona]
    new_X_test = []
    for i in range(0, 7):
        if(i<4):
            new_X_test.append(features[i])
        else:
            if(features[i] == 'singola' or features[i] == 'doppia'):
                if(features[i] == 'singola'):
                    new_X_test.append(0)
                    new_X_test.append(1)
                if(features[i] == 'doppia'):
                    new_X_test.append(1)
                    new_X_test.append(0)
            if(features[i] == 'F' or features[i] == 'M' or features[i] == 'M/F'):
                if(features[i] == 'F'):
                    new_X_test.append(1)
                    new_X_test.append(0)
                    new_X_test.append(0)
                if(features[i] == 'M'):
                    new_X_test.append(0)
                    new_X_test.append(1)
                    new_X_test.append(0)
                if(features[i] == 'M/F'):
                    new_X_test.append(0)
                    new_X_test.append(0)
                    new_X_test.append(1)
            if(features[i] == 'Barca' or features[i] == 'Bolognina' or features[i] == 'Borgo Panigale' or
                features[i] == 'Colli' or features[i] == 'Corticella' or features[i] == 'Costa Saragozza' or
                features[i] == 'Galvani' or features[i] == 'Irnerio' or features[i] == 'Lame' or
                features[i] == 'Malpighi' or features[i] == 'Marconi' or features[i] == 'Mazzini' or
                features[i] == 'Murri' or features[i] == 'S.Ruffillo' or features[i] == 'S.Viola' or
                features[i] == 'S.Vitale' or features[i] == 'Saffi' or features[i] == 'San Donato'):
                if(features[i] == 'Barca'):
                    new_X_test.append(1)
                    for o in range(0,17):
                        new_X_test.append(0)
                if(features[i] == 'Bolognina'):
                    new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range(0,16):
                        new_X_test.append(0)
                if(features[i] == 'Borgo Panigale'):
                    for o in range(0,2):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,15):
                        new_X_test.append(0)
                if(features[i] == 'Colli'):
                    for o in range(0,3):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,14):
                        new_X_test.append(0)
                if(features[i] == 'Corticella'):
                    for o in range(0,4):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,13):
                        new_X_test.append(0)
                if(features[i] == 'Costa Saragozza'):
                    for o in range(0,5):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,12):
                        new_X_test.append(0)
                if(features[i] == 'Galvani'):
                    for o in range(0,6):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,11):
                        new_X_test.append(0)
                if(features[i] == 'Irnerio'):
                    for o in range(0,7):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,10):
                        new_X_test.append(0)
                if(features[i] == 'Lame'):
                    for o in range(0,8):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,9):
                        new_X_test.append(0)
                if(features[i] == 'Malpighi'):
                    for o in range(0,9):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,8):
                        new_X_test.append(0)
                if(features[i] == 'Marconi'):
                    for o in range(0,10):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,7):
                        new_X_test.append(0)
                if(features[i] == 'Mazzini'):
                    for o in range(0,11):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,6):
                        new_X_test.append(0)
                if(features[i] == 'Murri'):
                    for o in range(0,12):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,5):
                        new_X_test.append(0)
                if(features[i] == 'S.Ruffillo'):
                    for o in range(0,13):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,4):
                        new_X_test.append(0)
                if(features[i] == 'S.Viola'):
                    for o in range(0,14):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,3):
                        new_X_test.append(0)
                if(features[i] == 'S.Vitale'):
                    for o in range(0,15):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    for o in range (0,2):
                        new_X_test.append(0)
                if(features[i] == 'Saffi'):
                    for o in range(0,16):
                        new_X_test.append(0)
                    new_X_test.append(1)
                    new_X_test.append(0)
                if(features[i] == 'San Donato'):
                    for o in range(0,17):
                        new_X_test.append(0)
                    new_X_test.append(1)
    new_X_test = np.transpose(new_X_test)
    print('new_X_test:{} '.format(new_X_test))
    return new_X_test

out = widgets.interactive_output(features, {'bagno': bagno, 'cucina': cucina, 'salotto': salotto,
                                            'balcone': balcone, 'tipologia': tipologia, 'genere': genere,
                                            'zona': zona, 'y_n': y_n})

widgets.HBox([widgets.VBox([bagno, cucina, salotto, balcone, tipologia, genere, zona, y_n]), out])

In [181]:
yes

Button(button_style='success', description='Sì', icon='check', style=ButtonStyle(), tooltip='Sì')